### ISSUE TITLE
`PyTNG.tell` counts from 1

### ISSUE THREAD

**Issue by jbarnoud** [MDAnalysis/pytng#17]
`PyTNG.tell` seems to count from 1 while everything else counts from 0:

```python
with pytng.TNGFile('/home/jon/dev/pytng/tests/reference_files/tng_example.tng') as tng:
    print(tng[9].step)  # 9
    print(tng.tell())  # 10
```

I guess this is because `tell` returns the step that is about to be read, which is the next compared to the current one. This is misleading because it is not what the docstring says, and also because I cannot use directly  the result of `tell` to later `seek` at the same frame. Also, it is different from the behaviour that is expected based on what files usually do:

```python
with open('any-file') as a:
    print(a.tell())  # 0
    a.seek(10)
    print(a.tell())  # 10
```

**Comment by kain88-de** [comment]
Tell works as it should. I do not see how tell/seek would work with your example? 

With the current code everything works fine

```python
with tng:
    tng.tell()  # 0
    tng.seek(10)  # I want to read frame 10 next
    tng.tell()  # 10
    frame = next(tng)
    frame.step  # and yeah I got frame 10
```

I assume you are confused because of the test that you have written to see if `tell` matches the current read frame. Then your current test is correct. When we read a frame in a loop then the internal step of the TNGFile is of course one larger then the step of the returned frame.

Is this still a problem for you?
